# Generated by Django 2.0 on 2017-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elf_id', models.IntegerField(default=10)),
                ('elf_phone', models.IntegerField(max_length=10)),
                ('elf_fname', models.CharField(max_length=20)),
                ('elf_lname', models.CharField(max_length=30)),
                ('elf_list', models.CharField(max_length=255)),
                ('elf_child', models.BooleanField(default=False)),
                ('elf_coal', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Elf_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elf_id', models.IntegerField(default=10)),
                ('mth_phone', models.IntegerField(max_length=10)),
                ('mth_fname', models.CharField(max_length=20)),
                ('mth_lname', models.CharField(max_length=30)),
                ('mth_list', models.CharField(max_length=255)),
                ('mth_child', models.BooleanField(default=False)),
            ],
        ),
    ]
